import assert from "node:assert/strict";
import test from "node:test";
import { ESCALATION_ROLES, bindEscalationRoute, evaluateEscalationRoute, verifyEscalation } from "../src/control/escalation-route.mjs";
import { HANDOFF_ACCEPTANCE_LADDER } from "../src/control/sod-rules.mjs";
const d = (x = {}) => ({ delegation_id: "del-1", version: 1, project_id: "p", work_package_id: "wp", session_id: "s", source_actor_id: "producer", escalation_route: "GOV", ...x });
const i = (x = {}) => ({ delegationCandidate: d(), escalationActorRole: "GOV", escalationActorId: "gov-1", ...x });
const id = { decisionId: "dec-1", actorId: "gov-1", authorityRef: "grant-1", evidenceRefs: ["ev-1"], decidedAt: "2026-07-21T05:00:00Z", validFrom: "2026-07-21T05:00:00Z", validUntil: "2026-07-22T05:00:00Z" };
const q = { exactDelegationId: "del-1", exactDelegationVersion: 1, escalationActorRole: "GOV", escalationActorId: "gov-1" };
test("roles derive from shared handoff ladder", () => assert.deepEqual(ESCALATION_ROLES, Object.keys(HANDOFF_ACCEPTANCE_LADDER)));
test("authorized route evaluates frozen", () => { const r = evaluateEscalationRoute(i()); assert.equal(r.ok, true); assert.ok(Object.isFrozen(r)); });
test("shared aliases normalize", () => assert.equal(evaluateEscalationRoute(i({ escalationActorRole: "governance" })).ok, true));
test("undeclared or non-independent route denies", () => { assert.equal(evaluateEscalationRoute(i({ escalationActorRole: "QA" })).code, "DENY_ROUTE_NOT_AUTHORIZED"); assert.equal(evaluateEscalationRoute({ ...i(), delegationCandidate: d({ escalation_route: "ENGIN" }), escalationActorRole: "ENGIN" }).code, "DENY_ROUTE_NOT_AUTHORIZED"); });
test("self escalation denies", () => assert.equal(evaluateEscalationRoute(i({ escalationActorId: "producer" })).code, "DENY_SELF_ESCALATION"));
test("malformed inputs deny", () => { assert.equal(evaluateEscalationRoute().code, "DENY_MALFORMED_DELEGATION"); assert.equal(evaluateEscalationRoute(i({ escalationActorId: "" })).code, "DENY_MALFORMED_ROUTE"); });
test("binding mints frozen GOVERNANCE candidate", () => { const r = bindEscalationRoute(i(), id); assert.equal(r.decision_type, "GOVERNANCE"); assert.equal(r.outcome, "ESCALATION_BOUND"); assert.ok(Object.isFrozen(r)); });
test("denial cannot mint bound outcome", () => assert.equal(bindEscalationRoute(i({ escalationActorId: "producer" }), id).outcome, "DENY_SELF_ESCALATION"));
test("exact bind verifies", () => assert.deepEqual(verifyEscalation(bindEscalationRoute(i(), id), q), { ok: true }));
test("replay dimensions deny", () => { const r = bindEscalationRoute(i(), id); for (const x of [{ ...q, exactDelegationId: "x" }, { ...q, exactDelegationVersion: 2 }, { ...q, escalationActorRole: "QA" }, { ...q, escalationActorId: "x" }]) assert.equal(verifyEscalation(r, x).code, "DENY_DELEGATION_MISMATCH"); });
test("unknown, malformed, wrong type and denial deny", () => { const r = bindEscalationRoute(i(), id); assert.equal(verifyEscalation(null, q).code, "DENY_UNKNOWN_ESCALATION"); assert.equal(verifyEscalation(r, {}).code, "DENY_MALFORMED_VERIFICATION_REQUEST"); assert.equal(verifyEscalation({ ...r, decision_type: "DISPOSITION" }, q).code, "DENY_WRONG_DECISION_TYPE"); assert.equal(verifyEscalation(bindEscalationRoute(i({ escalationActorId: "producer" }), id), q).code, "DENY_NOT_BOUND"); });
